export const SUPABASE_URL = 'https://yuhzgjqibvsdlaxjsbro.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1aHpnanFpYnZzZGxheGpzYnJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyNDk2MjAsImV4cCI6MjA5MjgyNTYyMH0.fk61ZfNl7QfYQmHHncnDuwPWu9z4Y5xr27dizsp0bZY';
